### ISSUE TITLE
Umbrella issues for benchmark tests

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-sigs/cri-tools#25]
Umbrella issues for benchmark tests.

- [ ] P0: Parallel Sandbox & containers operation
   - [x] Candidate Operation List (benchmark one operation in one test case):
        - [x] sandbox run #85 
        - [x] sandbox status
        - [x] remove sandbox
        - [x] stop sandbox
        - [x] list sandboxes
        - [x] create container #90 
        - [x] container status
        - [x] start container
        - [x] stop container
        - [x] remove container
        - [x] list container
    - [ ] Metrics:
        - [ ] Node: 
            - [ ] CPU usage (%)
            - [ ] MEM usage (%)
        - [ ] Runtime daemon perf: 
            - pod list latency (ms, 50%ile 90%ile 99%ile)
        - [ ] Core:
            - [ ] operation latency (ns, 50%ile 90%ile 99%ile)
    - [ ] Test Case Variable:
        - [ ] concurrency of operation
- [ ] p0: Image write operation (stick to specific image)
    - [ ] Candidate Operation List (benchmark one operation in one test case):
        - [ ] image pull
        - [ ] image remove
    - [ ] Metrics:
        - [ ] Node: 
            - [ ] CPU usage (%)
            - [ ] MEM usage (%)
            - [ ] DISK IO (%iowait)
            - [ ] NETWORK IO (bandwidth usage: bytes/sec)
    - [ ] Test Case Variable:
        - [ ] repeat number of operation
- [ ] p0: Image read operation (stick to specific image)
    - [ ] Candidate Operation List (benchmark one operation in one test case):
            - [ ] image list
            - [ ] image status
    - [ ] Metrics:
        - [ ] Node: 
            - [ ] CPU usage (%)
            - [ ] MEM usage (%)
        - [ ] Core:
            - [ ] operation latency (ns, 50%ile 90%ile 99%ile)
    - [ ] Test Case Variable:
        - [ ] repeat number of operation
- [ ] p0: Parallel image operation (stick to specific image)
    - [ ] Candidate Operation List (benchmark one operation in one test case):
        - [x] image pull
        - [x] image remove
        - [x] image list
    - [ ] Metrics:
        - [ ] Node: 
            - CPU usage (%)
            - MEM usage (%)
            - DISK IO (%iowait)
            - NETWORK IO (bandwidth usage: bytes/sec)
    - [ ] Test Case Variable:
        - concurrency of operation
- [ ] P2: Streaming (maybe next release)
    - Metrics:
        - Node: 
            - CPU usage (%)
            - MEM usage (%)
        - Core:
            - every Op latency (ms, 50%ile 90%ile 99%ile)
    - Operation:
        - Op = exec/attach/portforward
    - WorkFlow:
        - start -> run sandbox -> start container -> loop(parallel_do(exec -> attach -> portforward)) -> finish
    - Variable:
        - loop count
        - routine number
        - duration of every parrallel_do operation

See [more details](https://docs.google.com/document/d/1usdMWxOXvKIQ00UPRYQWNKY4jeL66FpbHnL7dz0m6qc/edit) about each test case.

cc/ @yujuhong @Random-Liu @mrunalp @xlgao-zju 

Would someone like to add the performance test framework?

**Comment by feiskyer** [comment]
We could do this via https://onsi.github.io/ginkgo/#benchmark-tests
